#!/bin/bash

python3 kNN.py ant-1.3.csv >> out.txt
python3 kNN.py ant-1.4.csv >> out.txt
python3 kNN.py ant-1.5.csv >> out.txt
python3 kNN.py ant-1.6.csv >> out.txt
python3 kNN.py ant-1.7.csv >> out.txt
python3 kNN.py camel-1.0.csv >> out.txt
python3 kNN.py camel-1.2.csv >> out.txt
python3 kNN.py camel-1.4.csv >> out.txt
python3 kNN.py camel-1.6.csv >> out.txt
python3 kNN.py ivy-1.4.csv >> out.txt
python3 kNN.py ivy-2.0.csv >> out.txt
python3 kNN.py jedit-3.2.csv >> out.txt
python3 kNN.py jedit-4.0.csv >> out.txt
python3 kNN.py jedit-4.1.csv >> out.txt
python3 kNN.py jedit-4.2.csv >> out.txt
python3 kNN.py jedit-4.3.csv >> out.txt
python3 kNN.py log4j-1.0.csv >> out.txt
python3 kNN.py log4j-1.1.csv >> out.txt
python3 kNN.py log4j-1.2.csv >> out.txt
python3 kNN.py lucene-2.0.csv >> out.txt
python3 kNN.py lucene-2.2.csv >> out.txt
python3 kNN.py lucene-2.4.csv >> out.txt
python3 kNN.py poi-1.5.csv >> out.txt
python3 kNN.py poi-2.0.csv >> out.txt
python3 kNN.py poi-2.5.csv >> out.txt
python3 kNN.py poi-3.0.csv >> out.txt
python3 kNN.py synapse-1.0.csv >> out.txt
python3 kNN.py synapse-1.1.csv >> out.txt
python3 kNN.py synapse-1.2.csv >> out.txt
python3 kNN.py velocity-1.4.csv >> out.txt
python3 kNN.py velocity-1.5.csv >> out.txt
python3 kNN.py velocity-1.6.csv >> out.txt
python3 kNN.py xalan-2.4.csv >> out.txt
python3 kNN.py xalan-2.5.csv >> out.txt
python3 kNN.py xalan-2.6.csv >> out.txt
python3 kNN.py xalan-2.7.csv >> out.txt
python3 kNN.py xerces-1.2.csv >> out.txt
python3 kNN.py xerces-1.3.csv >> out.txt
python3 kNN.py xerces-1.4.csv >> out.txt
